package constant

var (
	DefaultServerName  = []byte("simo-http")
	DefaultUserAgent   = []byte("simo-http")
	DefaultContentType = []byte("text/plain; charset=utf-8")
)

var (
	StrSlash            = []byte("/")
	StrSlashSlash       = []byte("//")
	StrSlashDotDot      = []byte("/..")
	StrSlashDotSlash    = []byte("/./")
	StrSlashDotDotSlash = []byte("/../")
	StrCRLF             = []byte("\r\n")
	StrHTTP             = []byte("http")
	StrHTTPS            = []byte("https")
	StrHTTP11           = []byte("HTTP/1.1")
	StrColon            = []byte(":")
	StrColonSlashSlash  = []byte("://")
	StrColonSpace       = []byte(": ")
	StrGMT              = []byte("GMT")
	StrAt               = []byte("@")

	StrResponseContinue = []byte("HTTP/1.1 100 Continue\r\n\r\n")

	StrGet     = []byte(MethodGet)
	StrHead    = []byte(MethodHead)
	StrPost    = []byte(MethodPost)
	StrPut     = []byte(MethodPut)
	StrDelete  = []byte(MethodDelete)
	StrConnect = []byte(MethodConnect)
	StrOptions = []byte(MethodOptions)
	StrTrace   = []byte(MethodTrace)
	StrPatch   = []byte(MethodPatch)

	StrExpect           = []byte(HeaderExpect)
	StrConnection       = []byte(HeaderConnection)
	StrContentLength    = []byte(HeaderContentLength)
	StrContentType      = []byte(HeaderContentType)
	StrDate             = []byte(HeaderDate)
	StrHost             = []byte(HeaderHost)
	StrReferer          = []byte(HeaderReferer)
	StrServer           = []byte(HeaderServer)
	StrTransferEncoding = []byte(HeaderTransferEncoding)
	StrContentEncoding  = []byte(HeaderContentEncoding)
	StrAcceptEncoding   = []byte(HeaderAcceptEncoding)
	StrUserAgent        = []byte(HeaderUserAgent)
	StrCookie           = []byte(HeaderCookie)
	StrSetCookie        = []byte(HeaderSetCookie)
	StrLocation         = []byte(HeaderLocation)
	StrIfModifiedSince  = []byte(HeaderIfModifiedSince)
	StrLastModified     = []byte(HeaderLastModified)
	StrAcceptRanges     = []byte(HeaderAcceptRanges)
	StrRange            = []byte(HeaderRange)
	StrContentRange     = []byte(HeaderContentRange)
	StrAuthorization    = []byte(HeaderAuthorization)

	StrCookieExpires        = []byte("expires")
	StrCookieDomain         = []byte("domain")
	StrCookiePath           = []byte("path")
	StrCookieHTTPOnly       = []byte("HttpOnly")
	StrCookieSecure         = []byte("secure")
	StrCookieMaxAge         = []byte("max-age")
	StrCookieSameSite       = []byte("SameSite")
	StrCookieSameSiteLax    = []byte("Lax")
	StrCookieSameSiteStrict = []byte("Strict")
	StrCookieSameSiteNone   = []byte("None")

	StrClose               = []byte("close")
	StrGzip                = []byte("gzip")
	StrDeflate             = []byte("deflate")
	StrKeepAlive           = []byte("keep-alive")
	StrUpgrade             = []byte("Upgrade")
	StrChunked             = []byte("chunked")
	StrIdentity            = []byte("identity")
	Str100Continue         = []byte("100-continue")
	StrPostArgsContentType = []byte("application/x-www-form-urlencoded")
	StrMultipartFormData   = []byte("multipart/form-data")
	StrBoundary            = []byte("boundary")
	StrBytes               = []byte("bytes")
	StrTextSlash           = []byte("text/")
	StrApplicationSlash    = []byte("application/")
	StrBasicSpace          = []byte("Basic ")
)
